name: pDL
channels:
  - conda-forge
  - pytorch
  - dglteam
dependencies:
  - python=3.8
  - pip
  - matplotlib
  - jupyter
  - jupyterlab
  - pytorch
  - torchvision>=0.5
  - torchtext
  - opencv
  - librosa
  - nb_conda_kernels
  - dgl>=0.4.3
  - rich>=10.12
  - Flask>=2.0
  - pandas>=1.1
  - sklearn
  - pip:
    - torchviz
    - nbgitpuller
